services:
  - type: web
    name: speaker-recognition
    envVars:
      - key: RENDER_FFMPEG
        value: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT speaker_recognition:app
